config/routes.rb
Rails.application.routes.draw do
  root "kittens#index" # Set root ('/') to index view

  resources :kittens # All 7 RESTful actions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :age, presence: true
    validates :cuteness, presence: true
    validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    # Make data available in corresponding views
    # The forms in "new" and "edit" should be the same by using a partial
    # CSRF protection prevents you from creating, updating or deleting kittens via the API

    def index # Has a view because it's a GET request
        @kittens = Kitten.all # Return an enumerable object of all kittens
        
        respond_to do |format| # Respond with HTML or JSON
            format.html
            format.json { render :json => @kittens }
        end
    end

    def show # Has a view
        @kitten = Kitten.find(params[:id]) # Find by primary key, which is auto-generated by Rails

        respond_to do |format| # Respond with HTML or JSON
            format.html
            format.json { render :json => @kitten }
        end
    end

    def new # Has a view
        @kitten = Kitten.new # Render a form to accept new Kittens
    end

    def create
        @kitten = Kitten.new(kitten_params) # Create kitten from form submission

        if @kitten.save # If Kitten is able to be saved
            redirect_to @kitten # Redirect to Kitten post page
            flash[:saved] = "Successfully created a kitty!"
        else
            flash.now[:error] = "Something went wrong"
            render :new, status: :unprocessable_entity # Otherwise, send back to form with flash message
        end
    end

    def edit # Has a view
        @kitten = Kitten.find(params[:id]) # Look for ID in the URL as a query string, which is passed into Rails as part of the params hash, and make available in view
    end

    def update
        @kitten = Kitten.find(params[:id]) # Grab correct Kitten by ID in URL

        if @kitten.update(kitten_params) # If Kitten is able to be updated given the new form submission
            redirect_to @kitten # Redirect to Kitten post page
            flash[:updated] = "Successfully updated a kitty!"
        else
            flash.now[:error] = "Something went wrong"
            render :edit, status: :unprocessable_entity # Throw back to edit page with flash message
        end
    end
    
    def destroy
        @kitten = Kitten.find(params[:id]) # If a DELETE request is sent to the page for that kitten, find it by ID
        @kitten.destroy # Destroy record

        flash[:destroyed] = "You killed a kitty..."
        redirect_to root_path
    end

    private

    # Require Strong Params
    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
    <%= form.label :name, "Name: " %>
    <%= form.text_field :name %><br><br>
    <%= form.label :age, "Age: " %>
    <%= form.number_field :age, step: 1 %><br><br>
    <%= form.label :cuteness, "Cuteness: " %>
    <%= form.number_field :cuteness, in: 1..10, step: 1 %><br><br>
    <%= form.label :softness, "Softness: " %>
    <%= form.number_field :softness, in: 1..10, step: 1 %><br><br>
    <%= submit_tag("Submit") %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit details for <%= @kitten.name %></h1>

<%= render "form" %>

<br>

<%= link_to "Destroy kitten", kitten_path(@kitten), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>

<br>

<%= link_to "Return to kitten", kitten_path %>

<br><br>

<%= flash.now[:error] %>

app/views/kittens/index.html.erb
<%= flash[:destroyed] %>

<h1>Hum Kitties</h1>
<h2>Here u can view kitties..</h2>

<ol>
<% @kittens.each { |kitten| %>
    <li>
        <%= link_to kitten.name, kitten %>
        - <%= link_to "destroy", kitten, data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?" } %>
    </li>
<% } %>
</ol>

<%= link_to "New kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Make a hum kitty!</h1>

<%= render "form" %>

<br>

<%= link_to "Return home", root_path %>

<br><br>

<%= flash.now[:error] %>

app/views/kittens/show.html.erb
<%= flash[:saved] %>
<%= flash[:updated] %>

<h1>View details for <%= @kitten.name %></h1>

<p>Name: <%= @kitten.name %></p>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to "Edit kitten", edit_kitten_path %><br>
<%= link_to "Destroy kitten", kitten_path(@kitten), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } %>

<br><br>

<%= link_to "Return home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittensRestApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>